<Project>
  <PropertyGroup>
    <LockingGlassVersion>$([System.IO.File]::ReadAllText('$(MSBuildThisFileDirectory)VERSION').Trim())</LockingGlassVersion>
    <Version Condition="'$(Version)' == ''">$(LockingGlassVersion)</Version>
    <AssemblyVersion Condition="'$(AssemblyVersion)' == ''">$(LockingGlassVersion).0</AssemblyVersion>
    <FileVersion Condition="'$(FileVersion)' == ''">$(LockingGlassVersion).0</FileVersion>
    <InformationalVersion Condition="'$(InformationalVersion)' == ''">$(LockingGlassVersion)</InformationalVersion>
    <Company Condition="'$(Company)' == ''">Locking Glass Contributors</Company>
    <Product Condition="'$(Product)' == ''">Locking Glass</Product>
  </PropertyGroup>
</Project>
